name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialize
        run: |
          echo "Building LizBall keyboard firmware"
          cd $GITHUB_WORKSPACE
          ls -la
          ls -la config || true
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: Build firmware
        run: west build -s zmk/app -b seeeduino_xiao_ble -- -DSHIELD=lizball -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: List build outputs
        run: |
          find build -name "*.uf2" -type f || true
          find build/zephyr -type f -name "*.uf2" || true
      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: lizball-firmware
          path: |
            build/zephyr/zmk.uf2